/**
 * Read-only task catalog for getModuleCatalog (`sdk.capability_tasks.gen1`).
 * Keep in sync with frontend `TASK_CAPABILITY_MANIFESTS` (audit:capability-tasks).
 */
export type TaskCatalogEntry = {
  taskId: string;
  domain: string;
  comfortBudget: number;
  executionMode: 'inline' | 'split' | 'immersive' | 'companion';
  shells: Array<'dev' | 'user'>;
};

export const TASK_CATALOG_METADATA: readonly TaskCatalogEntry[] = [
  { taskId: 'rag.collection_create', domain: 'rag.collection', comfortBudget: 2, executionMode: 'inline', shells: ['dev', 'user'] },
  { taskId: 'rag.ingest_text', domain: 'rag.document', comfortBudget: 3, executionMode: 'inline', shells: ['dev', 'user'] },
  { taskId: 'rag.search_smoke', domain: 'rag.search', comfortBudget: 2, executionMode: 'inline', shells: ['dev', 'user'] },
  { taskId: 'storage.upload', domain: 'storage.file', comfortBudget: 3, executionMode: 'inline', shells: ['dev', 'user'] },
  { taskId: 'storage.delete', domain: 'storage.file', comfortBudget: 3, executionMode: 'split', shells: ['dev', 'user'] },
  { taskId: 'storage.move', domain: 'storage.file', comfortBudget: 3, executionMode: 'split', shells: ['dev', 'user'] },
  { taskId: 'hosting.deploy_zip', domain: 'hosting.site', comfortBudget: 3, executionMode: 'split', shells: ['dev', 'user'] },
  { taskId: 'hosting.publish', domain: 'hosting.site', comfortBudget: 3, executionMode: 'split', shells: ['dev', 'user'] },
  { taskId: 'hosting.upgrade', domain: 'hosting.site', comfortBudget: 2, executionMode: 'split', shells: ['dev', 'user'] },
  { taskId: 'project_hosting.ladder_host', domain: 'hosting.project', comfortBudget: 2, executionMode: 'split', shells: ['dev', 'user'] },
  { taskId: 'project_hosting.complete_sell', domain: 'hosting.project', comfortBudget: 3, executionMode: 'split', shells: ['dev', 'user'] },
  { taskId: 'hosting.edit_file', domain: 'hosting.site.file', comfortBudget: 3, executionMode: 'split', shells: ['dev'] },
  { taskId: 'integrate.connect', domain: 'integrations.connection', comfortBudget: 3, executionMode: 'split', shells: ['dev'] },
  { taskId: 'integrate.select_events', domain: 'integrations.connection', comfortBudget: 2, executionMode: 'split', shells: ['dev', 'user'] },
  { taskId: 'agents.automate_bind', domain: 'agents.agent', comfortBudget: 2, executionMode: 'inline', shells: ['dev', 'user'] },
  { taskId: 'integrate.replay_delivery', domain: 'integrations.delivery', comfortBudget: 3, executionMode: 'split', shells: ['dev'] },
  { taskId: 'bots.manage', domain: 'bots.fleet', comfortBudget: 3, executionMode: 'split', shells: ['dev', 'user'] },
  { taskId: 'bots.quick_start', domain: 'bots.fleet', comfortBudget: 4, executionMode: 'split', shells: ['dev', 'user'] },
  { taskId: 'mentor.playground', domain: 'knowledge.platform', comfortBudget: 3, executionMode: 'split', shells: ['dev'] },
  { taskId: 'knowledge.playground', domain: 'knowledge.platform', comfortBudget: 3, executionMode: 'split', shells: ['dev'] },
  { taskId: 'knowledge.eval', domain: 'knowledge.platform', comfortBudget: 3, executionMode: 'split', shells: ['dev'] },
  { taskId: 'knowledge.acceptance.run', domain: 'knowledge.platform', comfortBudget: 3, executionMode: 'split', shells: ['dev'] },
  { taskId: 'knowledge.correction.propose', domain: 'knowledge.platform', comfortBudget: 2, executionMode: 'split', shells: ['dev'] },
  { taskId: 'knowledge.registry', domain: 'knowledge.platform', comfortBudget: 3, executionMode: 'split', shells: ['dev'] },
  { taskId: 'bots.connect.messaging', domain: 'bots.fleet', comfortBudget: 3, executionMode: 'split', shells: ['dev', 'user'] },
  { taskId: 'bots.attach_channel', domain: 'bots.fleet', comfortBudget: 3, executionMode: 'split', shells: ['dev'] },
  { taskId: 'bots.go_live', domain: 'bots.fleet', comfortBudget: 2, executionMode: 'split', shells: ['dev'] },
  { taskId: 'bots.launch_channel', domain: 'bots.fleet', comfortBudget: 3, executionMode: 'split', shells: ['dev', 'user'] },
  { taskId: 'bots.simulate_start', domain: 'bots.fleet', comfortBudget: 2, executionMode: 'inline', shells: ['dev', 'user'] },
  { taskId: 'bots.inbox', domain: 'bots.fleet', comfortBudget: 2, executionMode: 'split', shells: ['dev', 'user'] },
  { taskId: 'bots.commands', domain: 'bots.fleet', comfortBudget: 2, executionMode: 'split', shells: ['dev'] },
  { taskId: 'bots.knowledge.test', domain: 'bots.fleet', comfortBudget: 2, executionMode: 'split', shells: ['dev'] },
  { taskId: 'bots.policy', domain: 'bots.fleet', comfortBudget: 2, executionMode: 'split', shells: ['dev'] },
  { taskId: 'bots.knowledge.fill', domain: 'bots.fleet', comfortBudget: 2, executionMode: 'split', shells: ['dev'] },
  { taskId: 'bots.broadcast', domain: 'bots.fleet', comfortBudget: 3, executionMode: 'inline', shells: ['dev', 'user'] },
  { taskId: 'agents.create', domain: 'agents.agent', comfortBudget: 3, executionMode: 'immersive', shells: ['dev'] },
  { taskId: 'agents.run', domain: 'agents.agent', comfortBudget: 3, executionMode: 'split', shells: ['dev'] },
  { taskId: 'project.copilot.open', domain: 'agents.orchestrator', comfortBudget: 2, executionMode: 'inline', shells: ['dev', 'user'] },
  { taskId: 'agents.orchestrate', domain: 'agents.agent', comfortBudget: 3, executionMode: 'split', shells: ['dev', 'user'] },
  { taskId: 'crm.add_contact', domain: 'crm.contact', comfortBudget: 2, executionMode: 'inline', shells: ['dev', 'user'] },
  { taskId: 'crm.create_company', domain: 'crm.company', comfortBudget: 2, executionMode: 'inline', shells: ['dev', 'user'] },
  { taskId: 'crm.create_deal', domain: 'crm.deal', comfortBudget: 2, executionMode: 'inline', shells: ['dev', 'user'] },
  { taskId: 'crm.import_contacts', domain: 'crm.contact', comfortBudget: 3, executionMode: 'inline', shells: ['dev', 'user'] },
  { taskId: 'assets.create_digital', domain: 'commerce.asset', comfortBudget: 3, executionMode: 'split', shells: ['dev', 'user'] },
  { taskId: 'assets.manage_catalog', domain: 'commerce.asset', comfortBudget: 2, executionMode: 'split', shells: ['dev', 'user'] },
  { taskId: 'assets.publish_listing', domain: 'commerce.asset', comfortBudget: 2, executionMode: 'split', shells: ['dev', 'user'] },
  { taskId: 'commerce.bulk_seed_storefront', domain: 'commerce.asset', comfortBudget: 3, executionMode: 'split', shells: ['dev', 'user'] },
  { taskId: 'commerce.magic_fill_product', domain: 'commerce.asset', comfortBudget: 2, executionMode: 'split', shells: ['dev', 'user'] },
  { taskId: 'commerce.studio_quick_create', domain: 'commerce.asset', comfortBudget: 3, executionMode: 'split', shells: ['dev', 'user'] },
  { taskId: 'commerce.one_click_fill_catalog', domain: 'commerce.asset', comfortBudget: 2, executionMode: 'split', shells: ['dev', 'user'] },
  { taskId: 'commerce.studio_publish_vitrine', domain: 'commerce.asset', comfortBudget: 3, executionMode: 'split', shells: ['dev', 'user'] },
  { taskId: 'commerce.start_selling', domain: 'commerce.sell', comfortBudget: 2, executionMode: 'inline', shells: ['user', 'dev'] },
  { taskId: 'commerce.share_store', domain: 'commerce.sell', comfortBudget: 1, executionMode: 'inline', shells: ['user', 'dev'] },
  { taskId: 'commerce.manage_shelf', domain: 'commerce.sell', comfortBudget: 2, executionMode: 'split', shells: ['user', 'dev'] },
  { taskId: 'commerce.seller_orders', domain: 'commerce.sell', comfortBudget: 2, executionMode: 'split', shells: ['user', 'dev'] },
  { taskId: 'commerce.buy_listing', domain: 'commerce.storefront', comfortBudget: 3, executionMode: 'immersive', shells: ['user', 'dev'] },
  { taskId: 'commerce.hosted_storefront.open_demo', domain: 'commerce.storefront', comfortBudget: 2, executionMode: 'immersive', shells: ['user', 'dev'] },
  { taskId: 'commerce.surfaces.open_gallery', domain: 'commerce.storefront', comfortBudget: 2, executionMode: 'immersive', shells: ['user', 'dev'] },
  { taskId: 'commerce.embed.copy_buy_button', domain: 'commerce.storefront', comfortBudget: 2, executionMode: 'immersive', shells: ['user', 'dev'] },
  { taskId: 'commerce.lite.open_demo_store', domain: 'commerce.storefront', comfortBudget: 2, executionMode: 'immersive', shells: ['user', 'dev'] },
  { taskId: 'wallet.add_funds', domain: 'wallet.funding', comfortBudget: 3, executionMode: 'inline', shells: ['dev', 'user'] },
  { taskId: 'wallet.view_balance', domain: 'wallet.account', comfortBudget: 2, executionMode: 'inline', shells: ['dev', 'user'] },
  { taskId: 'wallet.pay_from_wallet', domain: 'wallet.payment', comfortBudget: 3, executionMode: 'inline', shells: ['dev', 'user'] },
  { taskId: 'project.settings.patch', domain: 'project.settings', comfortBudget: 3, executionMode: 'immersive', shells: ['dev'] },
  { taskId: 'project.delete.safe', domain: 'project.lifecycle', comfortBudget: 3, executionMode: 'immersive', shells: ['dev'] },
  { taskId: 'support.open_thread', domain: 'support.thread', comfortBudget: 3, executionMode: 'inline', shells: ['user'] },
  { taskId: 'logic.create_rule', domain: 'logic.rule', comfortBudget: 3, executionMode: 'inline', shells: ['dev'] },
  { taskId: 'logic.install_template', domain: 'logic.rule', comfortBudget: 2, executionMode: 'inline', shells: ['dev', 'user'] },
  { taskId: 'project.create', domain: 'project.lifecycle', comfortBudget: 2, executionMode: 'inline', shells: ['dev'] },
  { taskId: 'project.members.invite', domain: 'project.members', comfortBudget: 3, executionMode: 'immersive', shells: ['dev'] },
  { taskId: 'project.rbac.grant', domain: 'project.rbac', comfortBudget: 3, executionMode: 'immersive', shells: ['dev'] },
  { taskId: 'auth.fix_api_key', domain: 'auth.credentials', comfortBudget: 2, executionMode: 'inline', shells: ['dev'] },
  { taskId: 'auth.create_agent_key', domain: 'auth.credentials', comfortBudget: 2, executionMode: 'inline', shells: ['dev', 'user'] },
  { taskId: 'auth.create_user_pat', domain: 'auth.credentials', comfortBudget: 2, executionMode: 'inline', shells: ['dev', 'user'] },
  { taskId: 'fabric.marketplace.browse', domain: 'fabric.marketplace', comfortBudget: 3, executionMode: 'inline', shells: ['dev', 'user'] },
  { taskId: 'fabric.federation.grant', domain: 'fabric.federation', comfortBudget: 3, executionMode: 'inline', shells: ['dev', 'user'] },
  { taskId: 'fabric.hub.open', domain: 'fabric.hub', comfortBudget: 2, executionMode: 'inline', shells: ['dev', 'user'] },
  { taskId: 'fabric.notifications.inbox', domain: 'fabric.notifications', comfortBudget: 2, executionMode: 'inline', shells: ['dev', 'user'] },
  { taskId: 'fabric.moderator.inbox', domain: 'fabric.moderator', comfortBudget: 2, executionMode: 'inline', shells: ['dev'] },
  { taskId: 'operator.check_ecs_denorm', domain: 'operator.scale', comfortBudget: 2, executionMode: 'inline', shells: ['dev'] },
  { taskId: 'operator.review_bot_channels', domain: 'operator.fleet', comfortBudget: 2, executionMode: 'inline', shells: ['dev'] },
  { taskId: 'operator.open_attention_inbox', domain: 'operator.overview', comfortBudget: 2, executionMode: 'inline', shells: ['dev'] },
  { taskId: 'operator.review_fleet_runs', domain: 'operator.fleet', comfortBudget: 2, executionMode: 'inline', shells: ['dev'] },
  { taskId: 'operator.review_grant_readiness', domain: 'operator.grants', comfortBudget: 2, executionMode: 'inline', shells: ['dev'] },
  { taskId: 'operator.grants_os_pipeline', domain: 'operator.grants', comfortBudget: 3, executionMode: 'inline', shells: ['dev'] },
  { taskId: 'operator.review_scale_gates', domain: 'operator.scale', comfortBudget: 2, executionMode: 'inline', shells: ['dev'] },
  { taskId: 'operator.scale_neurocache_slo', domain: 'operator.scale', comfortBudget: 2, executionMode: 'inline', shells: ['dev'] },
  { taskId: 'operator.review_commerce_settlement', domain: 'operator.commerce', comfortBudget: 2, executionMode: 'inline', shells: ['dev'] },
  { taskId: 'operator.explore_gene_cache', domain: 'operator.scale', comfortBudget: 2, executionMode: 'inline', shells: ['dev'] },
  { taskId: 'operator.ecs_systems_health', domain: 'operator.scale', comfortBudget: 2, executionMode: 'inline', shells: ['dev'] },
  { taskId: 'operator.review_fleet_queue', domain: 'operator.fleet', comfortBudget: 2, executionMode: 'inline', shells: ['dev'] },
  { taskId: 'finance.top_up_card', domain: 'finance.payments', comfortBudget: 2, executionMode: 'split', shells: ['user', 'dev'] },
  { taskId: 'admin.ops.notifications', domain: 'operator.messaging', comfortBudget: 3, executionMode: 'inline', shells: ['dev'] },
  { taskId: 'admin.ops.delivery_logs', domain: 'operator.messaging', comfortBudget: 2, executionMode: 'inline', shells: ['dev'] },
  { taskId: 'mail.inbox.open', domain: 'social.mail', comfortBudget: 1, executionMode: 'immersive', shells: ['user', 'dev'] },
  { taskId: 'enroll-2fa', domain: 'auth.mfa', comfortBudget: 2, executionMode: 'inline', shells: ['user', 'dev'] },
  { taskId: 'connect-telegram-notify', domain: 'notify.sources', comfortBudget: 2, executionMode: 'inline', shells: ['user', 'dev'] },
  { taskId: 'generation.enable_safe_mode', domain: 'generation.settings', comfortBudget: 2, executionMode: 'inline', shells: ['dev'] },
  { taskId: 'generation.review_diff', domain: 'generation.promotion', comfortBudget: 3, executionMode: 'split', shells: ['dev'] },
  { taskId: 'generation.promote_canary', domain: 'generation.promotion', comfortBudget: 3, executionMode: 'inline', shells: ['dev'] },
  { taskId: 'generation.test_rollout', domain: 'generation.promotion', comfortBudget: 3, executionMode: 'inline', shells: ['dev'] },
  { taskId: 'business.command.overview', domain: 'business.command', comfortBudget: 1, executionMode: 'inline', shells: ['dev', 'user'] },
  { taskId: 'business.organs.attach', domain: 'business.organism', comfortBudget: 3, executionMode: 'inline', shells: ['dev', 'user'] },
  { taskId: 'business.create_composite', domain: 'business.organism', comfortBudget: 4, executionMode: 'inline', shells: ['dev', 'user'] },
  { taskId: 'business.configure_sharing', domain: 'business.organism', comfortBudget: 2, executionMode: 'inline', shells: ['dev', 'user'] },
  { taskId: 'business.treasury.glance', domain: 'business.organism', comfortBudget: 2, executionMode: 'inline', shells: ['dev', 'user'] },
  { taskId: 'business.tariff.configure', domain: 'business.organism', comfortBudget: 2, executionMode: 'inline', shells: ['dev', 'user'] },
  { taskId: 'business.list_project_for_sale', domain: 'business.organism', comfortBudget: 2, executionMode: 'inline', shells: ['dev', 'user'] },
  { taskId: 'services.hire_browse', domain: 'public.services', comfortBudget: 1, executionMode: 'inline', shells: ['dev', 'user'] },
  { taskId: 'services.submit_inquiry', domain: 'public.services', comfortBudget: 2, executionMode: 'inline', shells: ['dev', 'user'] },
];
